### ISSUE TITLE
Does not work with WP 6.0

### ISSUE THREAD

**Issue by nick6352683** [davidwebca/custom-editor-sidebar-width#4]
I found this plugin from the ACF Pro forums. I am very sorry to inform you that it is not compatible with WP 5.9. The setting shows up, I can move the slider, but the size of the sidebar never changes.

Thanks, I hope we can get a fix for this, it would be an awesome addition to Gutenberg.

**Comment by davidwebca** [comment]
Hi! I'm using this plugin every day with WP 5.9 and haven't had any issue so far. I've also just made a plain installation test to make sure no other plugin was conflicting and it does work well. Can you provide me with more information?

- What is your browser, its version and on what OS?
- Any lingering error message in the browser's JavaScript development console?
- Are all other plugins deactivated?

**Comment by nick6352683** [comment]
Thanks for the response. 

Chrome on Windows 10, Localhost Xampp PHP 7.4.x, I have the WP Beta plugin installed, so now it's WP 6.0-alpha..., I also deactivated all the plugins...

Chrome is finding one issue:

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

The script listed is at:

 http://localhost/wp58b/wp-admin/load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.0-alpha-52660

Which is a core file. I get the same results with Edge btw...

**Comment by davidwebca** [comment]
Mm so that's WP 6.0 then. There might be major ways on how the sidebars are implemented. I'll edit the title of the issue and come back to test on 6.0 when I have time.

**Comment by nick6352683** [comment]
No it's not... All if fine, and this plugin IS ASESOME. The theme I was using had a style-gutenberg.css file, which styles the Gutenberg editor. Inside this file there was a CSS rule of .edit-post-sidebar { width: 300px !important; }. Commenting this line solved the issue for me, so all is fine, and sorry that I wasted your valuable time... Have this in mind in case others might report similar issue in the future - I think it's safe to close this issue, and thanks for everything... This plugin should be in the core !

**Comment by davidwebca** [comment]
Don't worry, all is good! I'll consider adding !important myself to the plugin style or even simply add a note to the readme so that people check that out in case. Thank you for the follow up! 👍
